staging: ath6kl: Fix stack frame compilation errors
Large stackframes causing compilation failures in gcc 4.4.x:
drivers/staging/ath6kl/os/linux/ioctl.c: In function 'ar6000_ioctl':
drivers/staging/ath6kl/os/linux/ioctl.c:4673: error: the frame size of
1944 bytes is larger than 1024 bytes

Signed-off-by: Jin Hong <jinh@codeaurora.org>