msm: uncompress: Fix compilation issue for MSM_DEBUG_UART
When MSM_DEBUG_UART is selected, there are linking errors
arch/arm/boot/compressed/misc.o: error: undefined reference to
'outer_cache.

CRs-Fixed: 288496
Signed-off-by: Taniya Das <tdas@codeaurora.org>
(cherry picked from commit ef96a63e6b24f33228087f8a0461ab054f2843c2)

Change-Id: Id7f41b9045c2901f472b86bd80507b56314b464e

Signed-off-by: Sunil Joseph <sunilj@codeaurora.org>